# Generated by Django 4.1.13 on 2024-07-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytmain', '0002_playlist_playlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'video_url')},
        ),
    ]
