# Generated by Django 4.1.13 on 2024-07-08 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ytmain', '0003_alter_playlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queueitem',
            unique_together={('user', 'video_url')},
        ),
    ]
